spring:
  application:
    name: MAIN-SERVICE
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  circuitbreaker:
    instances:
      DATA-SERVICE:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      DATA-SERVICE:
        maxAttempts: 3
        waitDuration: 2s